set_property PACKAGE_PIN J15 [get_ports {duty_cycle[0]}]
set_property PACKAGE_PIN L16 [get_ports {duty_cycle[1]}]
set_property PACKAGE_PIN M13 [get_ports {duty_cycle[2]}]
set_property PACKAGE_PIN R15 [get_ports {duty_cycle[3]}]
set_property PACKAGE_PIN R17 [get_ports {duty_cycle[4]}]
set_property PACKAGE_PIN T18 [get_ports {duty_cycle[5]}]
set_property PACKAGE_PIN U18 [get_ports {duty_cycle[6]}]
set_property PACKAGE_PIN R13 [get_ports {duty_cycle[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {duty_cycle[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {duty_cycle[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {duty_cycle[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {duty_cycle[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {duty_cycle[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {duty_cycle[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {duty_cycle[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {duty_cycle[0]}]
set_property PACKAGE_PIN P18 [get_ports rst]
set_property PACKAGE_PIN H17 [get_ports pwm_out]

set_property PACKAGE_PIN E3 [get_ports clock]
set_property IOSTANDARD LVCMOS18 [get_ports clock]
set_property IOSTANDARD LVCMOS18 [get_ports pwm_out]
set_property IOSTANDARD LVCMOS18 [get_ports rst]
create_clock -period 10.000 -name clock -waveform {0.000 5.000} clock
